FROM node:13.10.1-alpine3.10

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

ARG PORT=4000
ENV PORT $PORT
EXPOSE $PORT 9229 9230

WORKDIR /usr/src/app

COPY package.json ./
RUN npm install

COPY . .

ENTRYPOINT [ "npm" ]
CMD [ "start" ] 